version: '3'
services:
  db:
    image: core/postgresql
  railsapp:
    image: dennisjbell/redmine
    ports:
      - 8000:8000
    volumes:
      - ./habitat:/conf
    command: --peer db --bind database:postgresql.default --config-from /conf
    links:
    - db
