version: '3'
services:
  db:
    image: core/postgresql
    volumes:
      - "./habitat/default.toml:/default.toml"
  railsapp:
    image: your_origin/widget_world
    ports:
      - 8000:8000
    links:
    - db
    command: --peer db --bind database:postgresql.default
